name: Continuous Deployment
on:
  push:
    branches:
      - "master"
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: npm ci && npm run build
      
      - name: Run ls
        run: ls
      
      - name: Run shell
        run: tree .
